# CLI
brew "gcc"
brew "colordiff"
brew "htop"
brew "lazygit"
brew "tree-sitter-cli"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "eza"
brew "less"
brew "podman"
# brew "cbonsai"
# brew "asciiquarium"
# brew "cmatrix"
# brew "asciinema"
# brew "croc"
# brew "ttyd"
# brew "subversion"
# brew "neofetch"
# brew "tree"

# Tools
brew "tmux"
brew "neovim"
brew "starship"
brew "stow"
brew "luarocks"
brew "mise"

# PHP
brew "php"
brew "composer"
tap "symfony-cli/tap"
brew "symfony-cli/tap/symfony-cli"

# Spring
tap "spring-io/tap"
brew "spring-io/tap/spring-boot"
brew "gradle"
brew "maven"

# Ruby
brew "libyaml"
brew "openssl@3"

cask_args appdir: "~/Applications", require_sha: true
cask "ghostty"
cask "zen"
