# $ mise ls-remote <tool>
[tools]
node = "26"
bun = "1"
ruby = "4.0.5"
java = [
  "temurin-26.0.1+8",
  "graalvm-community-25.0.1",
  "graalvm-community-21.0.2",
  "graalvm-community-17.0.9"
]
kotlin = "latest"
