# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Dont forget to "<prefix> I" babe
set -g prefix C-s
set -ga terminal-overrides ",*-256color*:Tc"
set-window-option -g mode-keys vi
set -g mouse off
set -g base-index 1

# Plugin init
set -g @plugin "tmux-plugins/tpm"

# Themes
set -g @plugin 'dracula/tmux'

# Dracula Colors - tailwind 700 for base colors, 500 for the main accent
set -g @dracula-colors "
# simple catppuccin Color Pallette
white='#ffffff'
neutral='#1d293d'
sky='#024a70'
blue='#1c398e'
violet='#4d179a'

# Dracula specific
gray='#020618'
dark_gray='#313244'
dark_purple='#f6339a'

orange='#7e2a0c'
pink='#c6005c'
green='#008236'
indigo='#432dd7'

yellow='#f9e2af'
cyan='#89dceb'
light_purple='#b4befe'
red='#f38ba8'
"
set -g @dracula-show-flags false

# Status bar
set -g @dracula-plugins "tmux-ram-usage cpu-usage ram-usage"
set -g @dracula-show-edge-icons true

set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label " "
set -g @dracula-tmux-ram-usage-label "󰞷 "
# set -g @dracula-git-label " "

# GIT
set -g @dracula-git-show-repo-name false
set -g @dracula-git-show-current-symbol 󰄬
set -g @dracula-git-show-diff-symbol 󰈅
set -g @dracula-git-disable-status true

set -g @dracula-git-colors "orange white"
set -g @dracula-cpu-usage-colors "pink white"
set -g @dracula-ram-usage-colors "green white"
set -g @dracula-tmux-ram-usage-colors "indigo white"

# "Reload" key bind
bind r source-file ~/.config/tmux/tmux.conf

unbind -n C-n
unbind -n C-l
unbind -n C-w
unbind x
unbind -n C-h
unbind t
unbind -n C-j
unbind -n C-k

bind-key -n C-l next-window
bind-key -n C-h previous-window

bind-key n new-window -c "#{pane_current_path}"
bind-key t split-window -h  -c "#{pane_current_path}"
bind-key x if-shell "[[ \$(tmux list-panes | wc -l) -gt 1 ]]" "kill-pane"
bind-key w kill-window

bind-key j select-pane -L
bind-key k select-pane -R

run "~/.tmux/plugins/tpm/tpm

# set -g @dracula-attached-clients-colors "cyan dark_gray"
# set -g @dracula-battery-colors "pink dark_gray"
# set -g @dracula-continuum-colors "cyan dark_gray"
# set -g @dracula-cpu-usage-colors "orange dark_gray"
# set -g @dracula-custom-plugin-colors "cyan dark_gray"
# set -g @dracula-cwd-colors "dark_gray white"
# set -g @dracula-fossil-colors "green dark_gray"
# set -g @dracula-git-colors "green dark_gray"
# set -g @dracula-gpu-power-draw-colors "green dark_gray"
# set -g @dracula-gpu-ram-usage-colors "cyan dark_gray"
# set -g @dracula-gpu-usage-colors "pink dark_gray"
# set -g @dracula-hg-colors "green dark_gray"
# set -g @dracula-kubernetes-context-colors "cyan dark_gray"
# set -g @dracula-libre-colors "white dark_gray"
# set -g @dracula-mpc-colors "green dark_gray"
# set -g @dracula-network-bandwidth-colors "cyan dark_gray"
# set -g @dracula-network-colors "cyan dark_gray"
# set -g @dracula-network-ping-colors "cyan dark_gray"
# set -g @dracula-network-vpn-colors "cyan dark_gray"
# set -g @dracula-playerctl-colors "green dark_gray"
# set -g @dracula-ram-usage-colors "cyan dark_gray"
# set -g @dracula-spotify-tui-colors "green dark_gray"
# set -g @dracula-ssh-session-colors "green dark_gray"
# set -g @dracula-synchronize-panes-colors "cyan dark_gray"
# set -g @dracula-terraform-colors "light_purple dark_gray"
# set -g @dracula-time-colors "dark_purple white"
# set -g @dracula-tmux-ram-usage-colors "cyan dark_gray"
# set -g @dracula-weather-colors "orange dark_gray"
